apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-python-sample-6raa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-python-sample-6raa
    app.kubernetes.io/part-of: rhtap-python-sample
  name: rhtap-python-sample-6raa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: rhtap-python-sample-6raa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: rhtap-python-sample-6raa
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rarnaud-tenant/rhtap-python-sample/rhtap-python-sample-6raa@sha256:f109b78e2cb5882152824570a6ef0db8515b991595d8bde2e5c755c811fd1607
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
