apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-default-pipeline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-default-pipeline
    app.kubernetes.io/part-of: rhtap-python-sample
  name: python-default-pipeline
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-default-pipeline
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-default-pipeline
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rarnaud-tenant/rhtap-python-sample/python-default-pipeline@sha256:91f3c1cb86c01184bff313091f1bfa5e18a573b2b7f4c083f1aa52ea23afa55a
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
